[package]
name = "spinfluent"
version = "0.1.0"
edition = "2021"
authors = ["protocolwhisper <protocol.eth@gmail.com>"] 
include = ["src/rust-template/**/*", "src/contract-templates/**/*", "src/js-template/**/*", "src/ts-template/**/*" , "src/contract-templates/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"


