[package]
name = "spinfluent"
version = "0.1.0"
edition = "2021"
authors = ["protocolwhisper <protocol.eth@gmail.com>"]
include = [
    "src/rust-template/**/*",
    "src/contract-templates/**/*",
    "src/js-template/**/*",
    "src/ts-template/**/*"
]



# Additional metadata (it's a good practice to fill these out)
description = "Tool for bootstraping Fluent projects"
license = "MIT" # Or your chosen license
repository = "https://github.com/protocolwhisper/spinfluent"

[dependencies]
dialoguer = "0.11.0"
